#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Sat Mar 31 20:25:42 2018

@author: ntlrsmllghn
"""

import numpy as np
import pandas as pd
import requests
import json

api_request = requests.get("https://api.conmarketcap.com/v1/ticker/")
api = json.loads(api_request.content)

print(api)
